spring:
  jpa:
    properties:
      hibernate:
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              host: http://localhost:9200
              index_schema_management_strategy: drop-and-create
              required_index_status: yellow